- name: Install required system packages
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: latest
    with_items:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python3-pip
      - virtualenv
      - python3-setuptools
  when: ansible_distribution == "Debian"

- name: Add Docker GPG apt Key
  apt_key:
    state: present
    url: https://download.docker.com/linux/ubuntu/gpg
  when: ansible_distribution == "Debian"

- name: Add Docker Repository
  apt_repository:
    state: present
    repo: deb https://download.docker.com/linux/ubuntu focal stable
  when: ansible_distribution == "Debian"

- name: Update apt and install docker-ce
  apt:
    name: docker-ce
    state: latest
    update_cache: true
  when: ansible_distribution == "Debian"

- name: Install Docker Module for Python
  pip:
    name: docker

- name: Pull default Docker image
  community.docker.docker_image:
    name: "{{ default_container_image }}"
    source: pull

- name: creating a docker container for webserver
  community.general.docker_container:
    name: webserver
    image: "{{ default_container_image }}"
    ports:
      - "80:80"
      - "443:443"
    state: started
    detach: yes
