---
- hosts: ubuntu
  become:
    true
  remote_user:
    ansible
  roles:
   - install_docker_ubuntu

- hosts: amazon
  become:
    true
  remote_user:
    ansible
  roles:
   - install_docker_amazon
